### ISSUE TITLE
Memory Leak?

### ISSUE THREAD

**Issue by drmbt** [DanielArnett/360-VJ#3]
When I drop this on my master output, (flat to fisheye), it does what its supposed to, but acts as if there are trails or feedback on... each frame is not being cleared and the image quickly just fills with information. Any suggestions?

**Comment by DanielArnett** [comment]
Interesting! Do the other shaders give problems? That might hint where the problem is. Toss this image in and see if you can get the fisheye rotation working.
![image](https://user-images.githubusercontent.com/3029502/47439023-97a52f80-d779-11e8-9fb7-0ffbac9606f9.png)

Can you grab a picture or video? What OS are you on?

**Comment by drmbt** [comment]
> 
> I had been working on a PC, just went to try it on a mac for kicks. All 4 plugins give the same results, and this time even more extreme; you can see a bunch of gpu memory garbage as soon as you drop any of the plugins in. somehow the cache isn’t getting cleared and everything is staying in GPU memory land. Here is a video for reference:

https://photos.app.goo.gl/1rzDiJ7qCWDdRCLo6

**Comment by DanielArnett** [comment]
Oh very interesting, I guess I never thought of that use case. My effects are intended for videos, but I don't see why they should give that behavior. So perhaps you could look upstream? [Maybe find one of leadedges effects and see if it works?](https://github.com/leadedge/ShaderMaker/tree/master/Binaries) If it's an issue with the upstream source I doubt I could be useful, but if it's something wrong with my ShaderToy shader (I think that's what I used) I might be able to fix it when I can get a break from school.
[Here's my code](https://github.com/DanielArnett/360-VJ/blob/9a4812c8ae11d7c54e90b15ca60b46cf6576fb0c/ShaderMaker.cpp#L646) (630-730), the rest is leadedge's wrapper to convert ShaderToy into FFGL.

**Comment by drmbt** [comment]
I’m not really a shaderboi, probably not something I could dig into myself. This seems to happen on any clip I drop it on; my use case it deform 2d video using flat to fisheye for a concave surface I’m projecting into tomorrow night. I just want it across the master channel to help confirm to the domed surface better.

Thanks!

**Comment by DanielArnett** [comment]
Since you're looking for quick hacks at this point here's my
recommendation: Pre-render the video and then apply my shader. Since my
shader is designed to work on videos it shouldn't have an issue with what
you're doing, then you can use Fisheye Rotation to position it in the dome
space.

**Comment by drmbt** [comment]
That won’t work, it’s a live VJ set, can’t be pre rendered. Worst case scenario I’ll just add some masking and go HAM on the bezier warping.  I’ll figure it out. Thanks

**Comment by DanielArnett** [comment]
So I dug in and found the issues. I was only retrieving the RBG values of the pixel and ignoring the alpha of the channel. Since in your use case the RGB didn't really change but the alpha did it gave that issue. Anyway that gave me the kick in the pants to really overhaul the code, making it leaner and faster. I'll be a while before can test and push the full release, but here's an early bird copy for you. Actually it's so early it might not work with the latest version of Resolume you might have to wait for them to push their next update (6.1.2, compatible with OpenGL 4.1), or just wait for my release.

[FlatToFisheye.zip](https://github.com/DanielArnett/360-VJ/files/2550924/FlatToFisheye.zip)

**Comment by DanielArnett** [comment]
Okay, fixed for Windows, OSX coming soon.

Here are the updated binaries for Resolume < 6.0.0
* [FFGL1.5 32 bit](https://github.com/DanielArnett/360-VJ/tree/master/binaries/FFGL1.5/x86/Release)
Here are the updated binaries for 6.0.0 <= Resolume < 6.1.2
* [FFGL 1.5 64 bit](https://github.com/DanielArnett/360-VJ/tree/master/binaries/FFGL1.5/x64/Release)
Here are the updated binaries for 6.1.2 <= Resolume
* [FFGL 3.0 64 bit](https://github.com/DanielArnett/360-VJ/tree/master/binaries/FFGL3/x64/Release)

Pick the version that corresponds to your version of Resolume.
